apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: g3f3wkpqi-go
  janus-idp.io/tekton: g3f3wkpqi-go
  backstage.io/kubernetes-id: g3f3wkpqi-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g3f3wkpqi-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
